apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-helmrepo
        namespace: flux-system
  targetNamespace: ingress-nginx
  values:
    controller:
      replicaCount: 1
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
      admissionWebhooks:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
