apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: monitoring
spec:
  provider:
    azurekv:
      vaultUrl: https://kv-kind024.vault.azure.net/
      tenantId: 8ab3a12a-d8b2-4792-b12b-68aeadeabd1c
      authType: ServicePrincipal
      environmentType: PublicCloud
      authSecretRef:
        clientId:
          name: azure-akv-secret
          key: clientId
        clientSecret:
          name: azure-akv-secret
          key: clientSecret
