apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    fluxcd.io/force-redeploy: "true"
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: "7.3.11"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: monitoring
  values:
    rbac:
      pspEnabled: false

    service:
      enabled: true
      type: ClusterIP
      port: 3000

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        # This annotation tells the NGINX ingress controller to rewrite the URL path of incoming requests to "/".
        # For example, if a request is made to "/app", it will be rewritten to "/".
        # This is commonly used when routing traffic to services that expect requests to start at the root path ("/").
        cert-manager.io/cluster-issuer: ca-issuer
      path: /
      pathType: Prefix
      hosts:
        - grafana.local
      tls: 
        - hosts:
            - grafana.local
          secretName: grafana-tls

    grafana.ini:
      server:
        root_url: "https://grafana.local"
        serve_from_sub_path: true

    admin:
      existingSecret: grafana-admin-secret
      userKey: admin-user
      passwordKey: admin-password
    
    podAnnotations:
     external-secrets.io/refresh-restarted-pods: "true"


resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
