apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-values
  namespace: podinfo
data:
  values.yaml: |
    replicaCount: 2
    ui:
      message: "Blue Deployment"
      color: "#007bff"
    podLabels:
      version: "blue"
    service:
      labels:
        version: "blue"
