name: Validate Kubernetes Manifests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          curl -s https://api.github.com/repos/yannh/kubeconform/releases/latest \
            | grep "browser_download_url.*linux-amd64.tar.gz" \
            | cut -d '"' -f 4 \
            | xargs curl -L | tar xz -C /usr/local/bin kubeconform

          curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest \
            | grep "browser_download_url.*linux_amd64.tar.gz" \
            | cut -d '"' -f 4 \
            | xargs curl -L | tar xz -C /usr/local/bin kustomize

          sudo apt-get update && sudo apt-get install -y yq

      - name: Run validation script
        run: ./scripts/validate.sh
